//! API handlers

pub mod acp;
pub mod agent_graph_mcp;
pub mod agent_pty;
pub mod agent_usage;
pub mod agents;
pub mod ai;
pub mod automations;
pub mod common;
pub mod config;
pub mod custom_agent;
pub mod env;
pub mod extension;
pub mod folder;
pub mod git;
pub mod hooks;
pub mod libraries;
pub mod marketplace;
#[cfg(feature = "perf-monitor")]
pub mod perf;
pub mod projects;
pub mod render;
pub mod skills;
pub mod statistics;
pub mod stats;
pub mod studio_common;
pub mod symbols;
pub mod taskgroups;
pub mod tasks;
pub mod terminal;
pub mod update;
pub mod url_metadata;
pub mod version;
pub mod walkie_talkie;
