//! Authentication module for Grove mobile access
//!
//! Supports two modes:
//! - **No auth** (`grove web`): all requests pass through
//! - **HMAC-SHA256** (`grove mobile`): every request must carry a valid signature;
//!   the secret key never travels over the wire

use axum::{
    body::Body,
    extract::{Json, Request},
    http::StatusCode,
    middleware::Next,
    response::{IntoResponse, Response},
};
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

type HmacSha256 = Hmac<Sha256>;

/// Label exposed to the frontend via `/auth/info`.
#[derive(Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AuthMode {
    None,
    Hmac,
}

/// Server authentication state.
pub struct ServerAuth {
    pub mode: AuthMode,
    /// `None` ⇒ no auth required.  `Some(sk)` ⇒ HMAC mode.
    pub secret_key: Option<String>,
    /// True when `secret_key` was generated by `generate_secret_key()` (i.e.
    /// the user accepted the auto-generate option at the interactive prompt).
    /// Used by the startup banner to warn that the key is ephemeral and
    /// won't survive restarts.
    pub key_is_generated: bool,
    /// Nonce replay-prevention map: nonce → timestamp (epoch secs).
    used_nonces: Mutex<HashMap<String, i64>>,
}

impl ServerAuth {
    /// No authentication (localhost / `grove web`).
    pub fn no_auth() -> Self {
        Self {
            mode: AuthMode::None,
            secret_key: None,
            key_is_generated: false,
            used_nonces: Mutex::new(HashMap::new()),
        }
    }

    /// HMAC-SHA256 authentication (`grove mobile`). `is_generated` should be
    /// true when the key came from `generate_secret_key()`, false when the
    /// user typed it at the interactive prompt.
    pub fn hmac(secret_key: String, is_generated: bool) -> Self {
        Self {
            mode: AuthMode::Hmac,
            secret_key: Some(secret_key),
            key_is_generated: is_generated,
            used_nonces: Mutex::new(HashMap::new()),
        }
    }

    /// Verify an HMAC-SHA256 signature.
    ///
    /// The message is `"{timestamp}|{nonce}|{METHOD}|{canonical_path}"`, where
    /// `canonical_path` is `path` plus a sorted, `&`-joined query string (see
    /// [`canonical_path`]). Caller is responsible for canonicalizing before
    /// passing the value in.
    pub fn verify_signature(
        &self,
        timestamp: &str,
        nonce: &str,
        method: &str,
        path: &str,
        signature: &str,
    ) -> bool {
        let sk = match &self.secret_key {
            Some(sk) => sk,
            None => return true, // no auth mode
        };

        // 1. Timestamp window check (±60 s)
        let ts: i64 = match timestamp.parse() {
            Ok(v) => v,
            Err(_) => return false,
        };
        let now = chrono::Utc::now().timestamp();
        if (now - ts).abs() > 60 {
            return false;
        }

        // 2. Nonce replay check
        {
            let mut nonces = self.used_nonces.lock().expect("nonce lock poisoned");

            if nonces.contains_key(nonce) {
                return false; // replay
            }

            // Record this nonce
            nonces.insert(nonce.to_string(), ts);

            // Purge stale nonces (> 120 s old)
            nonces.retain(|_, &mut t| (now - t).abs() <= 120);
        }

        // 3. Compute expected HMAC
        let message = format!("{}|{}|{}|{}", timestamp, nonce, method, path);
        let mut mac =
            HmacSha256::new_from_slice(sk.as_bytes()).expect("HMAC accepts any key length");
        mac.update(message.as_bytes());
        let expected = hex::encode(mac.finalize().into_bytes());

        // Constant-time-ish comparison (hex strings, both lowercase)
        expected == signature
    }
}

/// Generate a cryptographically random 64-character hex secret key.
pub fn generate_secret_key() -> String {
    let mut bytes = [0u8; 32];
    getrandom::getrandom(&mut bytes).expect("Failed to generate random bytes");
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

// ─── Middleware ──────────────────────────────────────────────────────────────

/// Extract a single value from a query string: `key=value&…`
fn query_param<'a>(query: &'a str, key: &str) -> Option<&'a str> {
    for part in query.split('&') {
        if let Some(value) = part
            .strip_prefix(key)
            .and_then(|rest| rest.strip_prefix('='))
        {
            if !value.is_empty() {
                return Some(value);
            }
        }
    }
    None
}

/// Build the canonical path-and-query used as the `path` segment of the HMAC
/// message. Query parameters are sorted by `(key, value)` ascending and
/// joined with `&`. `exclude_keys` are dropped (used to strip `ts/nonce/sig`
/// when validating WebSocket upgrade requests that carry the signature in
/// the query string itself). Returns just `path` when there is no remaining
/// query.
///
/// IMPORTANT: this canonicalization is **byte-level**, not semantic-URL.
/// We do not percent-decode keys or values, do not collapse `+` to space,
/// do not normalize empty values, and do not unify multiple slashes. The
/// client signing the request MUST emit the exact same bytes — produce its
/// query by sorting `(key, value)` pairs ascending and joining with `&`,
/// matching whatever percent-encoding the server will see in the URL.
/// Mismatches at this layer produce `401 Invalid signature` even though
/// the URLs are semantically equivalent.
pub fn canonical_path(path: &str, query: Option<&str>, exclude_keys: &[&str]) -> String {
    let q = match query {
        Some(q) if !q.is_empty() => q,
        _ => return path.to_string(),
    };
    let mut pairs: Vec<(&str, &str)> = Vec::new();
    for part in q.split('&') {
        if part.is_empty() {
            continue;
        }
        let (k, v) = match part.split_once('=') {
            Some((k, v)) => (k, v),
            None => (part, ""),
        };
        if exclude_keys.contains(&k) || k.starts_with("_sm_") {
            continue;
        }
        pairs.push((k, v));
    }
    if pairs.is_empty() {
        return path.to_string();
    }
    pairs.sort();
    let mut out = String::with_capacity(path.len() + q.len() + 1);
    out.push_str(path);
    out.push('?');
    for (i, (k, v)) in pairs.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        out.push_str(k);
        out.push('=');
        out.push_str(v);
    }
    out
}

/// Axum middleware — checks HMAC signature (headers or query params).
///
/// Uses `OriginalUri` so that the path seen here is the full request path
/// (e.g. `/api/v1/projects`) even when the middleware runs inside a `.nest()`.
pub async fn auth_middleware(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
    original_uri: axum::extract::OriginalUri,
    request: Request<Body>,
    next: Next,
) -> Response {
    // No-auth mode → pass through
    if auth.secret_key.is_none() {
        return next.run(request).await;
    }

    let method = request.method().as_str().to_uppercase();
    // Use the original (un-stripped) URI so the path matches what the client signed.
    let path = original_uri.path();
    let query = original_uri.query();

    // Try headers first. Header-signed requests include the full query string
    // in the canonical path (after sorting by key); no keys are excluded.
    let from_headers = (|| {
        let ts = request.headers().get("x-timestamp")?.to_str().ok()?;
        let nonce = request.headers().get("x-nonce")?.to_str().ok()?;
        let sig = request.headers().get("x-signature")?.to_str().ok()?;
        Some((ts.to_string(), nonce.to_string(), sig.to_string()))
    })();

    if let Some((ts, nonce, sig)) = from_headers {
        let canonical = canonical_path(path, query, &[]);
        if auth.verify_signature(&ts, &nonce, &method, &canonical, &sig) {
            return next.run(request).await;
        }
        return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
    }

    // Fallback: query params (WebSocket upgrade). The signature itself rides
    // on the URL as `ts/nonce/sig`, so we strip those three keys before
    // canonicalizing — otherwise the signature would have to sign itself.
    if let Some(query) = query {
        if let (Some(ts), Some(nonce), Some(sig)) = (
            query_param(query, "ts"),
            query_param(query, "nonce"),
            query_param(query, "sig"),
        ) {
            let canonical = canonical_path(path, Some(query), &["ts", "nonce", "sig"]);
            if auth.verify_signature(ts, nonce, &method, &canonical, sig) {
                return next.run(request).await;
            }
            return (StatusCode::UNAUTHORIZED, "Invalid signature").into_response();
        }
    }

    (StatusCode::UNAUTHORIZED, "Unauthorized").into_response()
}

#[derive(Serialize)]
pub struct AuthInfoResponse {
    pub required: bool,
    pub mode: AuthMode,
}

/// `GET /api/v1/auth/info` — tells the SPA whether auth is required and which mode.
pub async fn auth_info(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
) -> Json<AuthInfoResponse> {
    Json(AuthInfoResponse {
        required: auth.secret_key.is_some(),
        mode: auth.mode,
    })
}

#[derive(Deserialize)]
pub struct VerifyRequest {
    pub proof: String,
}

#[derive(Serialize)]
pub struct VerifyResponse {
    pub valid: bool,
}

/// `POST /api/v1/auth/verify` — client sends `HMAC(SK, "grove-verify")` as proof.
pub async fn auth_verify(
    axum::extract::State(auth): axum::extract::State<Arc<ServerAuth>>,
    Json(req): Json<VerifyRequest>,
) -> Result<Json<VerifyResponse>, StatusCode> {
    match &auth.secret_key {
        None => Ok(Json(VerifyResponse { valid: true })),
        Some(sk) => {
            let mut mac =
                HmacSha256::new_from_slice(sk.as_bytes()).expect("HMAC accepts any key length");
            mac.update(b"grove-verify");
            let expected = hex::encode(mac.finalize().into_bytes());

            if req.proof == expected {
                Ok(Json(VerifyResponse { valid: true }))
            } else {
                Err(StatusCode::UNAUTHORIZED)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::canonical_path;

    #[test]
    fn no_query() {
        assert_eq!(canonical_path("/a/b", None, &[]), "/a/b");
        assert_eq!(canonical_path("/a/b", Some(""), &[]), "/a/b");
    }

    #[test]
    fn single_param() {
        assert_eq!(
            canonical_path("/api/v1/x", Some("offset=0"), &[]),
            "/api/v1/x?offset=0"
        );
    }

    #[test]
    fn sorts_by_key() {
        let a = canonical_path("/x", Some("b=2&a=1&c=3"), &[]);
        let b = canonical_path("/x", Some("a=1&b=2&c=3"), &[]);
        let c = canonical_path("/x", Some("c=3&a=1&b=2"), &[]);
        assert_eq!(a, "/x?a=1&b=2&c=3");
        assert_eq!(a, b);
        assert_eq!(a, c);
    }

    #[test]
    fn excludes_keys() {
        let canonical = canonical_path(
            "/ws",
            Some("ts=1&offset=0&nonce=abc&sig=def"),
            &["ts", "nonce", "sig"],
        );
        assert_eq!(canonical, "/ws?offset=0");
    }

    #[test]
    fn exclude_all_leaves_path_only() {
        let canonical = canonical_path(
            "/ws",
            Some("ts=1&nonce=abc&sig=def"),
            &["ts", "nonce", "sig"],
        );
        assert_eq!(canonical, "/ws");
    }

    #[test]
    fn value_without_equals() {
        // `?flag` (no =) → key "flag", value ""
        assert_eq!(canonical_path("/x", Some("flag"), &[]), "/x?flag=");
    }

    #[test]
    fn ignores_waf_security_params() {
        assert_eq!(
            canonical_path("/x", Some("b=2&_sm_nck=1&a=1&_sm_byp=123"), &[]),
            "/x?a=1&b=2"
        );
    }
}
